(* generated by Ott 0.31, locally-nameless from: Stlc.ott *)
Require Import Bool.
Require Import Metalib.Metatheory.
Require Import List.
Require Import Ott.ott_list_core.

(** For F_p *)
Require Import Coqprime.elliptic.ZEll.
Require Import Coq.micromega.Lia.

Ltac invert H := inversion H; subst; clear H.
Ltac invert_log_solved H g := 
  solve [inversion H; fail; idtac "solved"] || invert H.

(** Nat *)
Lemma le_lt_Sn_m: forall (n m: nat), S n <= m -> n < m. lia. Qed.
