(* generated by Ott 0.31, locally-nameless from: Stlc.ott *)
Require Import Bool.
Require Import Metalib.Metatheory.
Require Import List.
Require Import Ott.ott_list_core.

(** For F_p *)
Require Import Coqprime.elliptic.ZEll.
Require Import Coq.ZArith.Znumtheory.
Require Import Coq.ZArith.BinInt.
Require Import Coq.ZArith.BinIntDef.
Import Z.

Ltac invert H := inversion H; subst; clear H.
Ltac invert_log_solved H g := 
  solve [inversion H; fail; idtac "solved"] || invert H.

